services:
  - type: web
    name: placasybonificaciones
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    branch: main
    envVars:
      - key: FLASK_ENV
        value: production
