services:
  - type: web
    name: placasybonificaciones
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: main
    envVars:
      - key: FLASK_ENV
        value: production


