services:
  - type: web
    name: placasybonificaciones
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    branch: main
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: djz7qvh0h
      - key: CLOUDINARY_API_KEY
        value: 179951398732257
      - key: CLOUDINARY_API_SECRET
        value: FzkwBK7bM4CIr_BbhTfXOepdFpw
      - key: RUTA_PDF
        value: /tmp/pdf
      - key: RUTA_GUARDADO_IMAGENES
        value: /tmp/images
